name: build

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout local repo
      uses: actions/checkout@v2

    - name: Checkout git-sync repo
      uses: actions/checkout@v2
      with:
        repository: kubernetes/git-sync
        path: git-sync
        fetch-depth: 0

    - name: Login to Docker Hub
      run: |
        docker login \
          -u ${{ secrets.DOCKER_USERNAME }} \
          -p ${{ secrets.DOCKER_TOKEN }}

    - name: Set tag
      run: |
        echo "IMAGE_TAG=$( \
          cd git-sync; \
          git describe --tags --abbrev=0 \
          | sed 's/,/./g; s/v//')" \
          >> $GITHUB_ENV

    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build \
          -t raylas/git-sync:latest \
          -t raylas/git-sync:${{ env.IMAGE_TAG }} \
          .

    - name: Push image
      run: |
        docker push raylas/git-sync:latest
        docker push raylas/git-sync:${{ env.IMAGE_TAG }}
